// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/n0vReR9l61K
//  * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
//  */

// /** Add fonts into your Next.js project:

// import { Arimo } from 'next/font/google'
// import { IBM_Plex_Sans } from 'next/font/google'

// arimo({
//   subsets: ['latin'],
//   display: 'swap',
// })

// ibm_plex_sans({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link";

// import { Card, CardContent } from "@/components/ui/card";

// import Header from "./Header";
// import { Footer, Newsarticles } from "./footerCom";

// export function Newsarticle() {
//   return (
//     <div className="flex flex-col min-h-screen">
//       <Header />
//       <main className="flex-1">
//         <section className="bg-muted py-12 md:py-16 lg:py-20">
//           <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 lg:gap-16">
//             <div className="order-2 md:order-1">
//               <img
//                 src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                 width={800}
//                 height={500}
//                 alt="Hero Image"
//                 className="rounded-lg object-cover w-full h-[300px] md:h-[400px] lg:h-[500px]"
//                 style={{ aspectRatio: "800/500", objectFit: "cover" }}
//               />
//             </div>
//             <div className="order-1 md:order-2 flex flex-col justify-center">
//               <div className="space-y-4">
//                 <div className="inline-block rounded-lg bg-[#4169E1] px-3 py-1 text-sm text-white">
//                   Breaking News
//                 </div>
//                 <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl lg:text-6xl">
//                   Groundbreaking Discovery in Medical Research
//                 </h1>
//                 <p className="text-muted-foreground md:text-lg">
//                   Scientists uncover a revolutionary treatment that could
//                   transform the lives of millions. Read the full story to learn
//                   more.
//                 </p>
//               </div>
//               <div className="mt-6">
//                 <Link
//                   href="#"
//                   className="inline-flex h-10 items-center justify-center rounded-md bg-[#4169E1] px-6 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#4169E1]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                   prefetch={false}
//                 >
//                   Read More
//                 </Link>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section className="py-12 md:py-16 lg:py-20">
//           <div className="container mx-auto">
//             <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 1"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     Innovative Tech Startup Secures Funding
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     A promising new tech company has secured a significant
//                     investment, paving the way for rapid growth and innovation
//                     in the industry.
//                   </p>
//                 </CardContent>
//               </Card>
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 2"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     Sports Team Wins Championship Title
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     After a hard-fought season, the local sports team has
//                     emerged victorious, bringing home the coveted championship
//                     trophy.
//                   </p>
//                 </CardContent>
//               </Card>
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 3"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     New Environmental Regulations Announced
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     The government has introduced a set of new environmental
//                     regulations aimed at reducing carbon emissions and promoting
//                     sustainable practices.
//                   </p>
//                 </CardContent>
//               </Card>
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 4"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     Celebrity Announces Charity Initiative
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     A well-known public figure has launched a new charitable
//                     organization, aiming to make a positive impact on
//                     underprivileged communities.
//                   </p>
//                 </CardContent>
//               </Card>
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 5"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     Groundbreaking Scientific Discovery
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     Researchers have made a significant breakthrough in their
//                     field, unveiling a discovery that could have far-reaching
//                     implications.
//                   </p>
//                 </CardContent>
//               </Card>
//               <Card className="rounded-lg overflow-hidden">
//                 <img
//                   src="https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg"
//                   width={400}
//                   height={225}
//                   alt="News Article 6"
//                   className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
//                   style={{ aspectRatio: "400/225", objectFit: "cover" }}
//                 />
//                 <CardContent className="p-4 md:p-6">
//                   <h3 className="text-lg font-bold mb-2">
//                     New Legislation Aims to Improve Education
//                   </h3>
//                   <p className="text-muted-foreground line-clamp-3">
//                     The government has introduced a new bill that aims to reform
//                     the education system, focusing on improving accessibility
//                     and quality.
//                   </p>
//                 </CardContent>
//               </Card>
//             </div>
//           </div>
//         </section>
//       </main>
//       <Newsarticles />
//       <Footer />
//     </div>
//   );
// }

// Articles.tsx
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";

// Assuming these icon components are defined somewhere in your project
import {
  HomeIcon,
  NewspaperIcon,
  LaptopIcon,
  TrophyIcon,
  FilmIcon,
} from "@/components/icons";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function Newsarticles() {
  // Sample article data (replace with your actual data fetching logic)
  const articles = [
    {
      id: 1,
      title: "Innovative Tech Startup Secures Funding",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "A promising new tech company has secured a significant investment, paving the way for rapid growth and innovation in the industry.",
    },
    {
      id: 2,
      title: "Sports Team Wins Championship Title",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "After a hard-fought season, the local sports team has emerged victorious, bringing home the coveted championship trophy.",
    },
    {
      id: 3,
      title: "Sports Team Wins Championship Title",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "After a hard-fought season, the local sports team has emerged victorious, bringing home the coveted championship trophy.",
    },
    {
      id: 4,
      title: "Sports Team Wins Championship Title",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "After a hard-fought season, the local sports team has emerged victorious, bringing home the coveted championship trophy.",
    },
    {
      id: 5,
      title: "Sports Team Wins Championship Title",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "After a hard-fought season, the local sports team has emerged victorious, bringing home the coveted championship trophy.",
    },
    {
      id: 6,
      title: "Sports Team Wins Championship Title",
      imageUrl:
        "https://t3.ftcdn.net/jpg/03/27/55/60/360_F_327556002_99c7QmZmwocLwF7ywQ68ChZaBry1DbtD.jpg",
      summary:
        "After a hard-fought season, the local sports team has emerged victorious, bringing home the coveted championship trophy.",
    },
    // ... more articles (add your actual article data here)
  ];

  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        {/* ... (hero section content - You'll need to add this part based on your design) ... */}

        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
              {articles.map((article) => (
                <Card key={article.id} className="rounded-lg overflow-hidden">
                  <img
                    src={article.imageUrl}
                    width={400}
                    height={225}
                    alt={article.title}
                    className="w-full h-[200px] md:h-[150px] lg:h-[180px] object-cover"
                    style={{ aspectRatio: "400/225", objectFit: "cover" }}
                  />
                  <CardContent className="p-4 md:p-6">
                    <h3 className="text-lg font-bold mb-2">{article.title}</h3>
                    <p className="text-muted-foreground line-clamp-3">
                      {article.summary}
                    </p>
                    {/* Add a Link component to navigate to the full article */}
                    <Link href={`/article/${article.id}`}>Read More</Link>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>

      <aside className="bg-muted border-t py-8 px-6 md:px-8 lg:px-10">
        <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
          <div className="space-y-4">
            <h3 className="text-lg font-bold">Categories</h3>
            <nav className="space-y-2">
              <Link
                href="#"
                className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                <HomeIcon className="w-4 h-4" />
                Academics
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                <NewspaperIcon className="w-4 h-4" />
                Research
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                <LaptopIcon className="w-4 h-4" />
                Admissions
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                <TrophyIcon className="w-4 h-4" />
                Campus Life
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4"
                prefetch={false}
              >
                <FilmIcon className="w-4 h-4" />
                Alumni
              </Link>
            </nav>
          </div>
          <div className="space-y-4">
            <h3 className="text-lg font-bold">Popular Articles</h3>
            <div className="space-y-4">
              {/* ... (popular article previews) ... */}
            </div>
          </div>
          <div className="space-y-4">
            <h3 className="text-lg font-bold">Newsletter</h3>
            <p className="text-muted-foreground">
              Subscribe to our newsletter to stay up-to-date with the latest
              news and updates.
            </p>
            <form className="flex gap-2">
              <Input
                type="email"
                placeholder="Enter your email"
                className="flex-1"
              />
              <Button type="submit">Subscribe</Button>
            </form>
          </div>
        </div>
      </aside>
    </div>
  );
}
//maximum range error
